services:
  app:
    container_name: OctaCatbot-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: OctaCatbot:latest
    volumes:
      - app_data:/app  
      - yarn_cache:/root/.cache/yarn  
    environment:
      NODE_ENV: "production"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

    command: ["node", "."]
    
volumes:
  app_data: 
  yarn_cache: 
