services:
  app:
    container_name: OctaCatbot-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: OctaCatbot:latest
    volumes:
      - app_data:/app  
      - yarn_cache:/root/.cache/yarn
    env_file:
    - .env
    environment:
      NODE_ENV: "production"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GOOGLE_TRANSLATE_API_KEY:  ${GOOGLE_TRANSLATE_API_KEY}
      GOOGLE_TRANSLATE_API_URL: ${GOOGLE_TRANSLATE_API_URL}

    command: ["node", "."]
    
volumes:
  app_data: 
  yarn_cache: 
